# Copyright (c) 2026 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Input Processor for Auto Mouse Layer with toggle support

compatible: "zmk,input-processor-aml"

include: ip_two_param.yaml

properties:
  require-prior-idle-ms:
    type: int
    required: false
    default: 0
    description: Time in milliseconds that must pass after the last keystroke before the layer can be toggled

  excluded-positions:
    type: array
    required: false
    default: []
    description: Array of key positions that will NOT trigger layer deactivation when pressed
